name: catalogue build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
paths: ["voting"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ vars.docker_username }}
        password: ${{ secrets.docker_login }}
     
    - name: Build the Docker image
      run: |
        TAG=$(date +%Y%m%dT%H%M%S)
        docker build . --file voting/Dockerfile --tag lizzygetty/voting:$TAG
        docker push lizzygetty/voting:$TAG
       



        
          

    
    
